lollipopkit/flutter_gpt_box

lib/app.dart
lib/l10n/app_en.arb
lib/l10n/app_zh.arb
lib/view/page/backup/impl/webdav.dart
lib/view/page/home/appbar.dart
lib/view/page/home/bottom.dart
lib/view/page/home/chat.dart
lib/view/page/home/history.dart
lib/view/page/home/home.dart
lib/view/page/home/req.dart
lib/view/page/res.dart
lib/view/page/setting.dart
lib/view/widget/code.dart
pubspec.lock
pubspec.yaml

opt.: only auto wrap code blocks

---

lib/data/store/setting.dart
lib/l10n/app_en.arb
lib/l10n/app_zh.arb
lib/view/page/home/chat.dart
lib/view/page/setting.dart
lib/view/widget/code.dart

new: option of scroll switch chat

---

lib/core/util/chat_title.dart

opt.: claude title generation prompt

---

lib/view/page/setting.dart
pubspec.lock
pubspec.yaml

new: custom avatar emoji

---

lib/core/util/tool.dart
lib/core/util/tool.p.dart
lib/data/model/chat/history.view.dart
lib/view/page/home/chat.dart
lib/view/page/home/ctrl.dart
lib/view/page/home/req.dart
pubspec.lock
pubspec.yaml

feat: tool log & fix: title gen

---

README.md
README_zh.md
lib/core/util/tool.p.dart
lib/view/page/home/req.dart

fix: replay should rm the next tool/assist msg

---

lib/view/page/home/bottom.dart
lib/view/page/home/ctrl.dart

opt.: scroll bottom when IME opens

---

lib/app.dart
lib/data/store/setting.dart
lib/intro.dart
lib/l10n/app_en.arb
lib/l10n/app_zh.arb

feat: intro page

---

lib/view/page/image.dart
lib/view/widget/image.dart
pubspec.lock
pubspec.yaml

feat: save img

---

lib/core/util/api_balance.dart
lib/data/model/chat/config.dart
lib/data/res/openai.dart
lib/l10n/app_en.arb
lib/l10n/app_zh.arb
lib/view/page/profile.dart

feat: balance inquiry

---

lib/data/model/chat/config.dart
lib/l10n/app_en.arb
lib/l10n/app_zh.arb
lib/view/page/profile.dart

feat: edit cfg name

---

.github/workflows/release.yaml
lib/core/util/api_balance.dart
lib/l10n/app_en.arb
lib/l10n/app_zh.arb
lib/view/page/home/enum.dart
lib/view/page/profile.dart

fix: no add btn for profiles

---

lib/data/res/openai.dart
lib/main.dart
pubspec.lock
pubspec.yaml

fix: app data dir

---

lib/view/page/res.dart

bug: after a delete in res page, items display wrongly

---

lib/core/util/api_balance.dart

fix: chatanywhere balance api

---

lib/data/model/chat/history/history.dart
lib/data/model/chat/history/history.g.dart
lib/main.dart
lib/view/page/home/bottom.dart
lib/view/page/home/req.dart

opt.: option `useTools`(single chat scope)

---

lib/data/model/chat/history/history.dart
lib/data/model/chat/history/history.g.dart
lib/view/page/home/chat.dart
lib/view/page/home/req.dart

opt.: option `ignoreContextConstraint`

---

lib/core/util/api_balance.dart
lib/core/util/chat_title.dart
lib/data/res/openai.dart
lib/view/page/profile.dart
pubspec.lock
pubspec.yaml

opt.: only clear models list if url is diff

---

lib/l10n/app_en.arb
lib/l10n/app_zh.arb
lib/main.dart
lib/view/page/home/ctrl.dart
lib/view/page/home/drawer.dart
lib/view/page/home/var.dart

feat: add a switch of no confirmation on deleting chats in 30s

---

lib/data/res/url.dart
lib/view/page/home/req.dart

fix: carried history for req not correct

---

lib/data/res/openai.dart
lib/view/page/home/home.dart

fix: profileId not changed after restoring bak

---

lib/data/store/setting.dart
lib/view/page/home/drawer.dart
lib/view/page/home/home.dart
lib/view/page/profile.dart
lib/view/page/setting.dart
lib/view/page/tool.dart
macos/Podfile.lock
pubspec.lock
pubspec.yaml

opt.: use multi columns to improve screen space utilization on desktop

---

lib/data/model/chat/history/view.dart
lib/main.dart
lib/view/page/home/chat.dart
lib/view/page/home/ctrl.dart
macos/Flutter/GeneratedPluginRegistrant.swift
macos/Podfile.lock
macos/Runner/AppDelegate.swift
pubspec.lock
pubspec.yaml

bug: chat scroll view can't scroll to bottom correctly

---

lib/view/page/home/ctrl.dart
lib/view/page/home/home.dart

rm: dup chats deletion

---

lib/data/model/chat/history/history.ext.dart
lib/view/page/backup/view.dart
lib/view/page/home/req.dart
lib/view/page/settings/def.dart
lib/view/page/settings/setting.dart

bug: can't save chats after ending the stream

---

.gitignore
lib/data/model/chat/config.dart
lib/data/model/chat/config.g.dart
lib/view/page/home/appbar.dart
lib/view/page/home/bottom.dart
lib/view/page/settings/profile.dart

opt.: rm img/audio mode

---

lib/data/model/chat/github_model.dart
lib/data/model/chat/github_model.g.dart
lib/data/res/migrations.dart
lib/data/res/openai.dart
lib/data/res/url.dart
lib/view/page/settings/profile.dart

fix: compatibility of Github models

---

lib/data/res/openai.dart
lib/view/page/home/appbar.dart
lib/view/page/home/ctrl.dart
lib/view/page/settings/profile.dart

fix: can't load models for deepseek beta

---

lib/core/util/api_balance.dart
lib/data/model/chat/history/history.ext.dart
lib/data/res/migrations.dart
lib/data/res/openai.dart
lib/main.dart
lib/view/page/home/appbar.dart
lib/view/page/home/bottom/bottom.dart
lib/view/page/home/chat.dart
lib/view/page/home/ctrl.dart
lib/view/page/home/enum.dart
lib/view/page/home/file_picked.dart
lib/view/page/home/home.dart
lib/view/page/home/req.dart
lib/view/page/home/search.dart
lib/view/page/home/url_scheme.dart
lib/view/page/home/var.dart
lib/view/page/settings/profile.dart

fix: can't stop the chat stream

---

lib/view/page/home/bottom/bottom.dart
lib/view/page/home/bottom/settings.dart
lib/view/page/home/chat.dart
lib/view/page/home/ctrl.dart
lib/view/page/home/enum.dart
lib/view/page/home/home.dart
lib/view/page/home/req.dart
lib/view/page/home/var.dart

opt.: value node `_curChatId`

---

pubspec.lock
pubspec.yaml

new: sort of models

---

lib/view/page/home/ctrl.dart

fix: can't share chats as pic

---

lib/data/model/chat/config.dart
lib/data/res/openai.dart
lib/main.dart
lib/view/page/home/appbar.dart
lib/view/page/home/ctrl.dart
lib/view/page/home/enum.dart
lib/view/page/home/history.dart
lib/view/page/home/req.dart
lib/view/page/settings/setting.dart
pubspec.lock
pubspec.yaml

fix: model name not refreshed

---

lib/view/page/home/chat.dart
lib/view/widget/code.dart

new: copy btn of code block

---

lib/app.dart
lib/view/page/home/appbar.dart
lib/view/page/home/md_copy.dart
lib/view/page/settings/setting.dart

fix: desktop app window title bar
